#ifdef SIMPLIFIED

#define FOREGROUND_BLUE FB
#define FOREGROUND_GREEN FG
#define FOREGROUND_RED FR
#define FOREGROUND_INTENSITY FI

#define BACKGROUND_BLUE BB
#define BACKGROUND_GREEN BG
#define BACKGROUND_RED BR
#define BACKGROUND_INTENSITY BI

#else 

#define SIMPLIFIED 

#endif